# Generated by Django 4.1.7 on 2023-03-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='length_of_workout',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='resistance',
            field=models.CharField(max_length=50),
        ),
    ]
