# Generated by Django 4.1.7 on 2023-03-01 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_exercise_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='length_of_workout',
        ),
    ]
